name: Destroy 

# This workflow is triggered manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Safety check. Type the word "destroy" to confirm.'
        required: true
        default: 'do-not-destroy'
  #push:
   #     branches:
    #      - main
     #   paths:
      #    - "environments/dev/**"
       #   - "modules/**"
        #  - "src/**"
      

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    env:
      AWS_REGION: "us-east-1"
      # This TF_VAR is used in the safety check step
      CONFIRMATION_PHRASE: "destroy"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Safety Check
        id: safety_check
        run: |
          if [ "${{ github.event.inputs.confirmation }}" == "${CONFIRMATION_PHRASE}" ]; then
            echo "Confirmation matches. Proceeding with destroy."
          else
            echo "Error: Confirmation phrase does not match. Expected '${CONFIRMATION_PHRASE}' but got '${{ github.event.inputs.confirmation }}'."
            exit 1
          fi

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve 